### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by robotortoise** [uyjulian/PaperMarioModelViewer#1]
Hi, could you please make a GUI or at least drag and drop usability for this viewer? I'd like to view the models and animations to help TCRF on their Paper Mario pages, but I'm not quite sure how to, well, compile.

**Comment by uyjulian** [comment]
https://github.com/uyjulian/PaperMarioModelViewer/blob/master/README.md#building
There is a GUI.
Also, animations are currently not supported.

**Comment by robotortoise** [comment]
Oh, okay. It looks like I'd have to compile it, though.

**Comment by uyjulian** [comment]
Yes, you have to compile it, because I don't want to provide binaries for many different OS. (I only have cross compiler installed for Linux and FreeBSD)

**Comment by robotortoise** [comment]
OK.
