### ISSUE TITLE
errors when make is run

### ISSUE THREAD

**Issue by arzamas-16** [uyjulian/PaperMarioModelViewer#3]
i am a whole newbie at building and compiling programs, and i'd like to see if i could get some help with this. i'm getting errors (seen below) when i try to run make. do you think you could tell me how i should have the folders arranged, as most of these are related to how a directory is not found? 

![grafik](https://user-images.githubusercontent.com/37526427/37635657-5bbd754c-2bd3-11e8-9004-1f638c11d541.png)

**Comment by uyjulian** [comment]
Currently, the program only works on macOS.
I'm planning to write a Blender import plugin, but I doubt that it will get done anytime soon.

**Comment by arzamas-16** [comment]
ah, i see. thanks for the clarification
